

-- 
-- Database: `songs270`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `songs_phrases`
-- 

DROP TABLE IF EXISTS `songs_phrases`;
CREATE TABLE `songs_phrases` (
  `id` int(11) NOT NULL auto_increment,
  `name` text NOT NULL,
  `value` text NOT NULL,
  `cat` text NOT NULL,
  PRIMARY KEY  (`id`)
)  AUTO_INCREMENT=548 ;

-- 
-- Dumping data for table `songs_phrases`
-- 

INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (1, 'the_songs', '«·√€«‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (2, 'the_singers', '«·„€‰ÌÌ‰', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (3, 'the_songs_count', '⁄œœ «·√€«‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (4, 'the_albums_count', '⁄œœ «·√·»Ê„« ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (5, 'last_update', '¬Œ—  ÕœÌÀ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (6, 'contact_us', '«·≈ ’«· »‰«', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (7, 'no_results', '·«  ÊÃœ ‰ «∆Ã', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (8, 'search_results', '‰ «∆Ã «·»ÕÀ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (9, 'download', ' Õ„Ì·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (10, 'listen', '«” „«⁄', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (11, 'vote_song', ' ﬁÌÌ„ «·√€‰Ì…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (12, 'send2friend', '«—”«· ·’œÌﬁ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (13, 'lyrics', 'ﬂ·„«  «·√€‰Ì…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (14, 'watch', '„‘«Âœ…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (15, 'vote_video', ' ﬁÌÌ„ «·›ÌœÌÊ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (16, 'err_no_page', '⁄›Ê« , Â–Â «·’›Õ… €Ì— „ÊÃÊœ…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (17, 'type_search_keyword', 'ﬁ„ »ﬂ «»… ‘Ì¡ ··»ÕÀ ⁄‰Â ·« Ìﬁ· ⁄‰ {letters} √Õ—›', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (18, 'the_name', '«·≈”„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (19, 'add_date', ' «—ÌŒ «·≈÷«›…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (20, 'err_no_videos', '·«  ÊÃœ ﬂ·Ì»«   Õ  Â–« «·ﬁ”„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (21, 'err_wrong_url', '—«»ÿ Œ«ÿÌ¡', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (22, 'err_no_cats', '⁄›Ê« , ·«  ÊÃœ «ﬁ”«„ Â‰«', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (23, 'another_songs', '«€«‰Ì «Œ—Ï', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (24, 'pages', '«·’›Õ« ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (25, 'err_no_songs', '·«  ÊÃœ √€«‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (26, 'the_writer', '«·ﬂ« »', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (27, 'the_news_archive', '√—‘Ì› «·√Œ»«—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (28, 'vote_song_thnx_msg', '‘ﬂ—« ·ﬂ .. ·ﬁœ  „  ﬁÌÌ„ «·√€‰Ì…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (29, 'vote_video_thnx_msg', '‘ﬂ—« ·ﬂ .. ·ﬁœ  „  ﬁÌÌ„ «·ﬂ·Ì»', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (30, 'vote_select', '«· ﬁÌÌ„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (31, 'vote_do', ' ﬁÌÌ„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (32, 'send2friend_subject', 'œ⁄Ê… „‰ ’œÌﬁﬂ ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (33, 'send2friend_done', '·ﬁœ  „ «—”«· «·œ⁄Ê…  ·’œÌﬁﬂ ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (34, 'your_name', '«”„ﬂ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (35, 'your_email', '»—Ìœﬂ «·≈·ﬂ —Ê‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (36, 'your_friend_email', '»—Ìœ ’œÌﬁﬂ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (37, 'send', '«—”«·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (38, 'err_vote_expire_hours', '⁄›Ê« , Ì„ﬂ‰ﬂ «· ’ÊÌ  ﬂ· {vote_expire_hours} ”«⁄… ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (39, 'add2favorite', '«÷«›… «·Ï «·„›÷·…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (40, 'add2fav_success', ' „  «·«÷«›… «·Ï «·„›÷·…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (41, 'register_closed', '⁄›Ê« , «· ”ÃÌ· „€·ﬁ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (42, 'no_news', '·«  ÊÃœ √Œ»«—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (43, 'err_vote_file_expire_hours', '⁄›Ê« , Ì„ﬂ‰ﬂ  ﬁÌÌ„ «·„·› ﬂ· {vote_expire_hours} ”«⁄… ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (44, 'the_phrases', '«·⁄»«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (45, 'welcome_to_cp', '√Â·« »ﬂ ›Ì ·ÊÕ… «· Õﬂ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (46, 'php_version', '≈’œ«— PHP', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (47, 'mysql_version', '≈’œ«— MySQL', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (48, 'zend_version', '≈’œ«— Zend Optimizer', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (49, 'the_version', '«·«’œ«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (50, 'cp_available', '„ Ê›—…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (51, 'cp_not_available', '€Ì— „ Ê›—…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (52, 'gd_library', '„ﬂ »… GD', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (53, 'gd_install_required', 'ÌÃ» ⁄·Ìﬂ  À»Ì  „ﬂ »… GD ·ﬂÌ Ì⁄„· «·”ﬂ—Ì»  ⁄·Ï ”Ì—›—ﬂ »‘ﬂ· ÃÌœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (54, 'cp_addons', '«·≈÷«›« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (55, 'no_addons', '·«  ÊÃœ «÷«›« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (56, 'edit', ' ⁄œÌ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (57, 'register', '«· ”ÃÌ·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (58, 'register_email_exists', 'Œÿ√ :  Â–« «·»—Ìœ „ÊÃÊœ „”»ﬁ« <br>  «–« ﬂ«‰ Â–« ÂÊ »—Ìœﬂ «·«·ﬂ —Ê‰Ì Ê ‰”Ì»  ﬂ·„… «·„—Ê—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (59, 'register_user_exists', '⁄›Ê« .. «”„ «·„” Œœ„ {username} „ÊÃÊœ „”»ﬁ« , Ì—ÃÏ «” Œœ«„ «”„ „” Œœ„ ¬Œ—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (60, 'reg_complete', '·ﬁœ  „ «ﬂ„«· ⁄„·Ì… «· ”ÃÌ· »‰Ã«Õ . ”Ê› Ì „ «—”«· —”«·… «·Ï »—Ìœ «·«·ﬂ —Ê‰Ì  Õ ÊÌ ⁄·Ï —«»ÿ  ›⁄Ì· «‘ —«ﬂﬂ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (61, 'err_fileds_not_complete', ' √ﬂœ „‰  ⁄»∆… Ã„Ì⁄ «·ÕﬁÊ·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (62, 'err_passwords_not_match', 'ﬂ·„… «·„—Ê— Ê  √ﬂÌœÂ« €Ì— „ ÿ«»ﬁÌ‰', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (63, 'email', '«·»—Ìœ «·«·ﬂ —Ê‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (64, 'username', '«”„ «·„” Œœ„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (65, 'password', 'ﬂ·„… «·„—Ê—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (66, 'cp_login_do', ' ”ÃÌ· «·œŒÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (67, 'cp_username', '«”„ «·„” Œœ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (68, 'cp_password', 'ﬂ·„… «·„—Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (69, 'the_content_type', '‰Ê⁄ «·„Õ ÊÏ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (70, 'the_url', '«·—«»ÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (71, 'bnr_appearance_places', '„ﬂ«‰ «·ŸÂÊ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (72, 'bnr_appearance_pages', '’›Õ«  «·ŸÂÊ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (73, 'add_after_menu_number', '«÷«›… »⁄œ ﬁ«∆„… —ﬁ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (74, 'login_do', ' ”ÃÌ· «·œŒÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (75, 'bnr_ctype_code', 'ﬂÊœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (76, 'bnr_ctype_img', '’Ê—… / —«»ÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (77, 'the_code', '«·ﬂÊœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (78, 'bnr_open', '»«‰— › Õ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (79, 'bnr_close', '»«‰— ﬁ›·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (80, 'bnr_menu', '«⁄·«‰ ﬁ«∆„…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (81, 'bnr_header', '»«‰— ÂÌœ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (82, 'bnr_footer', '»«‰— ›Ê —', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (83, 'bnr_menu_pos', '›Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (84, 'the_left', '«·Ì”«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (85, 'the_center', '«·Ê”ÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (86, 'the_right', '«·Ì„Ì‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (87, 'bnr_the_menu', '«·ﬁ«∆„…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (88, 'bnr_the_visits', '«·“Ì«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (89, 'bnr_appearance_count', '„—«  «·ŸÂÊ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (90, 'add_button', '«÷«›…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (91, 'the_order', '«· — Ì»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (92, 'the_image', '«·’Ê—…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (93, 'the_title', '«·⁄‰Ê«‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (94, 'delete', 'Õ–›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (95, 'pages_lang', '·€… «·’›Õ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (96, 'pages_encoding', ' —„Ì“ «·’›Õ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (97, 'cp_enable_browsing', ' ’›Õ «·„Êﬁ⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (98, 'cp_opened', '„› ÊÕ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (99, 'cp_closed', '„€·ﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (100, 'cp_browsing_closing_msg', '—”«·… «·≈€·«ﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (101, 'site_closed_for_visitors', '«·„Êﬁ⁄ „€·ﬁ ··“Ê«—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (102, 'cp_mailing_sending_to', '„—«”·… ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (103, 'cp_send_as', '≈—”«· ﬂ‹', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (104, 'cp_as_email', '»—Ìœ «·ﬂ —Ê‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (105, 'next_page', '«·’›Õ… «· «·Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (106, 'failed', '›‘·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (107, 'cp_as_pm', '—”«·… Œ«’…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (108, 'cp_send_to', '≈—”«· «·Ï', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (109, 'all_members', 'Ã„Ì⁄ «·√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (110, 'one_member', '⁄÷Ê „Õœœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (111, 'sender_name', '«”„ «·„—”·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (112, 'sender_email', '»—Ìœ «·„—”·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (113, 'msg_type', '‰Ê⁄ «·—”«·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (114, 'msg_encoding', ' —„Ì“ «·—”«·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (115, 'msg_subject', '„Ê÷Ê⁄ «·—”«·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (116, 'start_from', '«·»œ¡ „‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (117, 'mailing_emails_perpage', '«·⁄œœ ﬂ· ’›Õ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (118, 'auto_pages_redirection', '«‰ ﬁ«·  ·ﬁ«∆Ì »Ì‰ «·’›Õ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (119, 'cp_url_fopen_disabled_msg', '«⁄œ«œ«  «·”Ì—›— ·«  ”„Õ »”Õ» „·› ⁄‰ ÿ—Ìﬁ —«»ÿ Œ«—ÃÌ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (120, 'err_url_x_invalid', '«·—«»ÿ {url} €Ì— ’ÕÌÕ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (121, 'local_file_uploader', '—›⁄ „‰ «·ÃÂ«“', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (122, 'external_file_uploader', '”Õ» „‰ —«»ÿ Œ«—ÃÌ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (123, 'cp_photo_resize_width', '⁄—÷', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (124, 'cp_photo_resize_hieght', 'ÿÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (125, 'view', '⁄—÷', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (126, 'members_mailing', '„—«”·… «·√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (127, 'yes', '‰⁄„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (128, 'no', '·«', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (129, 'cp_mng_members', '«œ«—… «·√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (130, 'members_custom_fields', '«·Œ«‰«  «·«÷«›Ì… ··√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (131, 'cp_members_remote_db', 'ﬁ«⁄œ… »Ì«‰«  Œ«—ÃÌ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (132, 'the_members', '«·√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (133, 'cp_add_new_template', '«÷«›… ﬁ«·» ÃœÌœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (134, 'the_description', '«·Ê’›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (135, 'cp_edit_templates', ' ⁄œÌ· «·ﬁÊ«·»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (136, 'main_page', '«·—∆Ì”Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (137, 'the_templates', '«·ﬁÊ«·»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (138, 'style_settings', '«⁄œ«œ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (139, 'add_style', '«÷«›… ” «Ì· ÃœÌœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (140, 'style_selectable', 'Ì„ﬂ‰ ··“Ê«— «Œ Ì«—Â', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (141, 'template_name', '«”„ «·ﬁ«·»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (142, 'template_description', 'Ê’› «·ﬁ«·»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (143, 'add_new_template', '«÷«›… ﬁ«·» ÃœÌœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (144, 'are_you_sure', 'Â· «‰  „ √ﬂœ ø', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (145, 'the_database', 'ﬁ«⁄œ… «·»Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (146, 'backup', '‰”Œ… «Õ Ì«ÿÌ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (147, 'db_repair_tables_do', '«’·«Õ «·Ãœ«Ê·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (148, 'cp_db_backup_do', '«Œ– ‰”Œ… «Õ Ì«ÿÌ… «·¬‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (149, 'the_file_path', '„”«— «·„·›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (150, 'db_backup_saveto_server', 'Õ›Ÿ «·‰”Œ… ›Ì «·”Ì—›—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (151, 'db_backup_saveto_pc', 'Õ›Ÿ «·‰”Œ… «·Ï «·ÃÂ«“', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (152, 'cp_db_backup', '‰”Œ… «Õ Ì«ÿÌ… „‰ ﬁ«⁄œ… «·»Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (153, 'the_size', '«·ÕÃ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (154, 'the_table', '«·ÃœÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (155, 'the_status', '«·Õ«·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (156, 'please_select_tables_to_rapair', 'Ì—ÃÏ «Œ Ì«— «·Ãœ«Ê· «·„—«œ «’·«ÕÂ«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (157, 'cp_repairing_table', '≈’·«Õ «·ÃœÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (158, 'done', ' „', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (159, 'cp_db_check_repair', '›Õ’ / «’·«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (160, 'backup_done_successfully', ' „  «·⁄„·Ì… »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (161, 'the_search', '«·»ÕÀ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (162, 'members_count', '⁄œœ «·√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (163, 'cp_remote_members_db', 'ﬁ«⁄œ… »Ì«‰«  √⁄÷«¡ Œ«—ÃÌ… ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (164, 'use_remote_db', '«” Œœ«„ ﬁ«⁄œ… »Ì«‰«  Œ«—ÃÌ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (165, 'db_host', '⁄‰Ê«‰ «·”Ì—›—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (166, 'db_name', '«”„ ﬁ«⁄œ… «·»Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (167, 'db_username', '«”„ „” Œœ„ «·»Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (168, 'members_table', 'ÃœÊ· «·√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (169, 'note', '„·«ÕŸ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (170, 'members_remote_db_wizzard_note', '⁄‰œ «” Œœ«„ ﬁ«⁄œ… »Ì«‰«  «⁄÷«¡ ÃœÌœ… ÌÃ» ⁄·Ìﬂ «” Œœ«„ „⁄«·Ã ﬁÊ«⁄œ »Ì«‰«  «·«⁄÷«¡ ·· √ﬂœ „‰  Ê«›ﬁ ﬁ«⁄œ… «·»Ì«‰«  Ê «⁄œ«œÂ« ··⁄„·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (171, 'members_remote_db_wizzard', '„⁄«·Ã ﬁÊ«⁄œ »Ì«‰«  «·√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (172, 'chng_field_type_success', ' „  €ÌÌ— ‰Ê⁄ «·Œ«‰… ›Ì ﬁ«⁄œ… «·»Ì«‰«  »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (173, 'chng_field_type_failed', '·„ Ì „ﬂ‰ «·”ﬂ—Ì»  „‰  €ÌÌ— ‰Ê⁄ «·Œ«‰… , Ì—ÃÏ  €ÌÌ—Â« ÌœÊÌ« „‰ „œÌ— ﬁ«⁄œ… «·»Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (174, 'add_field_failed', '·„ Ì „ﬂ‰ «·”ﬂ—Ì»  „‰ «÷«›… «·Œ«‰… , Ì—ÃÏ «÷«› Â« ÌœÊÌ« „‰ „œÌ— ﬁ«⁄œ… «·»Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (175, 'add_field_success', ' „  «÷«›… «·Œ«‰… «·Ï ﬁ«⁄œ… «·»Ì«‰«  »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (176, 'members_remote_db_compatible', 'ﬁ«⁄œ… «·»Ì«‰«  „ Ê«›ﬁ… „⁄ «·”ﬂ—Ì» ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (177, 'members_remote_db_uncompatible', 'ﬁ«⁄œ… «·»Ì«‰«  €Ì— „ Ê«›ﬁ… „⁄ «·”ﬂ—Ì»  , Ì—ÃÏ „—«Ã⁄… «·√Œÿ«¡ Ê «’·«ÕÂ„ À„ «⁄«œ… «·«Œ »«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (178, 'wrong_remote_db_name', '«”„ ﬁ«⁄œ… «·»Ì«‰«  Œ«ÿÌ¡ , Ì—ÃÏ «· √ﬂœ „‰Â', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (179, 'wrong_remote_db_connect_info', 'Œÿ√ «À‰«¡ «·« ’«· »«·ﬁ«⁄œ… , Ì—ÃÏ «· √ﬂœ „‰ »Ì«‰«  «·« ’«·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (180, 'members_remote_db_disabled', '«·‰Ÿ«„ €Ì— „›⁄·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (181, 'no_members_custom_fields', '·«  ÊÃœ Œ«‰«  «÷«›Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (182, 'add_member_custom_field', '«÷«›… Œ«‰… «÷«›Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (183, 'the_type', '«·‰Ê⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (184, 'textbox', '’‰œÊﬁ ‰’', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (185, 'textarea', '’‰œÊﬁ ‰’ „ ⁄œœ «·«”ÿ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (186, 'select_menu', 'ﬁ«∆„… „‰”œ·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (187, 'radio_button', '“— «Œ Ì«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (188, 'checkbox', 'Œ«‰… «Œ Ì«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (189, 'default_value_or_options', '«·ﬁÌ„… «·«› —«÷Ì… / «·ŒÌ«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (190, 'put_every_option_in_sep_line', '··ŒÌ«—«  Ì „ Ê÷⁄ ﬂ· ŒÌ«— ›Ì ”ÿ— ÃœÌœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (191, 'required', '„ÿ·Ê»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (192, 'addition_style', ' ‰”Ìﬁ «÷«›Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (193, 'addition_fields', '„⁄·Ê„«  «÷«›Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (194, 'this_member_not_exists', 'Â–« «·⁄÷Ê €Ì— „ÊÃÊœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (195, 'members_local_db_clean_wizzard', '„⁄«·Ã  ‰ŸÌ› Ãœ«Ê· «·«⁄÷«¡ «·„Õ·Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (196, 'members_local_db_clean_note', '⁄‰œ «” Œœ«„ ﬁ«⁄œ… »Ì«‰«  „Õ·Ì… «Ê Œ«—ÃÌ… Ì „  Œ“Ì‰ »Ì«‰«  «·Œ«‰«  «·«÷«›Ì… Ê «·„›÷·… Ê «·—”«∆· «·Œ«’… Ê €Ì—Â« ⁄·Ï »⁄÷ «·Ãœ«Ê· ›Ì ﬁ«⁄œ… «·»Ì«‰«  «·„Õ·Ì… , ·–·ﬂ Ì›÷·  ‰ŸÌ› Â–Â «·ÃœÊ«· · ”—Ì⁄ ⁄„· «·ﬁ«⁄œ… Ê  Ã‰»« ·⁄œ„ Õ’Ê· «Ì  œ«Œ· ›Ì «·»Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (197, 'members_local_db_clean_description', '”Ê› ÌﬁÊ„ «·„⁄«·Ã »Õ–› «Ì »Ì‰«    ⁄·ﬁ »«·√⁄÷«¡ ﬂ„« ÂÊ „Ê÷Õ , Ì—ÃÏ «· √ﬂœ «‰ «·Ãœ«Ê· «· «·Ì… ·«  Õ ÊÌ ⁄·Ï «Ì »Ì«‰«  ÷—Ê—Ì… À„ «·÷€ÿ ⁄·Ï “— «· ‰›Ì– ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (198, 'members_msgs_table', 'ÃœÊ· —”«∆· «·√⁄÷«¡ «·Œ«’…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (199, 'members_favorite_table', 'ÃœÊ· »Ì«‰«  «·„·›«  «·„›÷·… ··√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (200, 'members_custom_fields_table', 'ÃœÊ· »Ì«‰«  «·Œ«‰«  «·«÷«›Ì… ··√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (201, 'members_confirmations_table', 'ÃœÊ·  √ﬂÌœ«  «· €Ì—«  ··√⁄÷«¡', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (202, 'process_done_successfully', ' „  «·⁄„·Ì… »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (274, 'from', '„‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (275, 'plz_enter_username_and_pwd', 'Ì—ÃÏ «· √ﬂœ „‰ «œŒ«· «”„ «·„” Œœ„ Êﬂ·„… «·„—Ê—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (204, 'pwd_rest_request_msg_subject', 'ÿ·»  €ÌÌ— ﬂ·„… «·„—Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (205, 'rest_pwd_request_msg_sent', ' „ «—”«· —”«·… «·Ï »—Ìœﬂ «·«·ﬂ —Ê‰Ì  Õ ÊÌ —«»ÿ  €ÌÌ— ﬂ·„… «·„—Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (206, 'pwd_rest_done_msg_subject', 'ﬂ·„… „—Ê—ﬂ «·ÃœÌœ… !', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (207, 'pwd_rest_done', '·ﬁœ  „  €ÌÌ— ﬂ·„… „—Ê—ﬂ Ê «—”«· ﬂ·„… «·„—Ê— «·ÃœÌœ… «·Ï »—Ìœﬂ «·«·ﬂ —Ê‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (208, 'security_code', 'ﬂÊœ «· Õﬁﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (209, 'email_activation_msg_subject', ' ›⁄Ì· »—Ìœﬂ «·«·ﬂ —Ê‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (210, 'upload_file', '—›⁄ „·›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (211, 'search_do', '»ÕÀ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (212, 'birth', ' «—ÌŒ «·„Ì·«œ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (213, 'country', '«·œÊ·…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (214, 'select_from_menu', '«Œ — „‰ «·ﬁ«∆„…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (215, 'register_do', ' ”ÃÌ·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (216, 'registered_before', '«‰  „”Ã· ·œÌ‰« „”»ﬁ«', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (217, 'click_here', '«÷€ÿ Â‰«', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (218, 'forgot_pass', '‰”Ì  ﬂ·„… «·„—Ê— ø', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (219, 'login_info_sent', '·ﬁœ  „ «—”«· „⁄·Ê„«  «·œŒÊ· «·Ï »—Ìœﬂ «·«·ﬂ —Ê‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (220, 'email_not_exists', 'Œÿ√ : Â–« «·»—Ìœ €Ì— „”Ã· ·œÌ‰«', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (221, 'continue', '„ «»⁄…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (222, 'active_account', ' ›⁄Ì· «·«‘ —«ﬂ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (223, 'active_acc_succ', '·ﬁœ  „  ›⁄Ì· «‘ —«ﬂﬂ »‰Ã«Õ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (224, 'active_acc_err', '⁄›Ê« .. ·„ Ì „ «· ›⁄Ì· , ﬁœ ÌﬂÊ‰  „  ›⁄Ì·Â „”»ﬁ« √Ê Â‰«·ﬂ Œÿ√ ›Ì «·—«»ÿ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (225, 'login', ' ”ÃÌ· œŒÊ·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (226, 'newuser', '„” Œœ„ ÃœÌœ ø', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (227, 'err_function_usage_denied', 'Œÿ√ : ·« Ì„ﬂ‰ﬂ «” ⁄„«· «·œ«·…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (228, 'err_emails_not_match', '«·»—Ìœ «·≈·ﬂ —Ê‰Ì Ê  √ﬂÌœÂ €Ì— „ ÿ«»ﬁÌ‰', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (229, 'email_confirm', ' √ﬂÌœ «·»—Ìœ «·≈·ﬂ —Ê‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (230, 'err_sec_code_not_valid', 'ﬂÊœ «· Õﬁﬁ €Ì— ’ÕÌÕ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (231, 'registration', '«· ”ÃÌ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (232, 'as_every_cat_settings', '«⁄œ«œ«  ﬂ· ﬁ”„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (233, 'enabled_for_all', '„›⁄· ··ﬂ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (234, 'stng_download_for_members_only', '«· Õ„Ì· ··√⁄÷«¡ ›ﬁÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (235, 'security_code_in_registration', 'ﬂÊœ «· Õﬁﬁ ›Ì «· ”ÃÌ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (236, 'auto_email_activate', ' ›⁄Ì· «·»—Ìœ «·«·ﬂ —Ê‰Ì  ·ﬁ«∆Ì«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (237, 'username_min_letters', '«ﬁ· ⁄œœ Õ—Ê› ·≈”„ «·„” Œœ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (238, 'username_exludes', '«” À‰«∆«  «”„ «·„” Œœ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (239, 'emails_msgs_default_type', '‰Ê⁄ —”«∆· «·»—Ìœ «·«·ﬂ —Ê‰Ì «·«› —«÷Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (240, 'emails_msgs_default_encoding', ' —„Ì“ —”«∆· «·»—Ìœ «·«·ﬂ —Ê‰Ì «·«› —«÷Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (241, 'leave_blank_to_use_site_encoding', '« —ﬂÂ ›«—€« ·≈” Œœ«„  —„Ì“ «·„Êﬁ⁄ «·«› —«÷Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (242, 'uploader_system', '‰Ÿ«„ —›⁄ «·„·›« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (243, 'disable_uploader_msg', '—”«·… ⁄œ„ «· ›⁄Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (244, 'uploader_path', '„”«— «·—›⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (245, 'uploader_allowed_types', '«·√‰Ê«⁄ «·„”„ÊÕ —›⁄Â«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (246, 'enabled', '„›⁄·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (247, 'disabled', '„⁄ÿ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (248, 'password_confirm', ' √ﬂÌœ ﬂ·„… «·„—Ê—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (249, 'err_username_min_letters', '⁄œœ Õ—Ê› «”„ «·„” Œœ„ «ﬁ· „‰ «·„”„ÊÕ »Â', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (250, 'err_email_not_valid', '«·»—Ìœ «·«·ﬂ —Ê‰Ì €Ì— ’ÕÌÕ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (251, 'err_username_not_allowed', '«”„ «·„” Œœ„ €Ì— „”„ÊÕ »Â', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (252, 'reg_complete_need_activation', '·ﬁœ  „ «ﬂ„«· ⁄„·Ì… «· ”ÃÌ· »‰Ã«Õ . ”Ê› Ì „ «—”«· —”«·… «·Ï »—Ìœ «·«·ﬂ —Ê‰Ì  Õ ÊÌ ⁄·Ï —«»ÿ  ›⁄Ì· «‘ —«ﬂﬂ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (253, 'req_addition_info', '„⁄·Ê„«  «÷«›Ì… „ÿ·Ê»…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (254, 'not_req_addition_info', '„⁄·Ê„«  €Ì— „ÿ·Ê»…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (255, 'your_email_changed_successfully', ' „  €ÌÌ— »—Ìœﬂ «·«·ﬂ —Ê‰Ì »‰Ã«Õ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (256, 'this_account_already_activated', '⁄›Ê« , Â–« «·Õ”«»  „  ›⁄Ì·Â „”»ﬁ«', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (257, 'closed_account_cannot_activate', '⁄›Ê«, Â–« «·Õ”«» „€·ﬁ ·« Ì„ﬂ‰ﬂ  ›⁄Ì·Â', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (258, 'activation_msg_sent_successfully', '·ﬁœ  „ «—”«· —”«·…  ›⁄Ì· «·«‘ —«ﬂ «·Ï »—Ìœﬂ «·«·ﬂ —Ê‰Ì »‰Ã«Õ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (259, 'register_date', ' «—ÌŒ «· ”ÃÌ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (260, 'last_login', '¬Œ— œŒÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (261, 'member_deleted_successfully', ' „ Õ–› «·⁄÷Ê »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (262, 'member_added_successfully', ' „ «÷«›… «·⁄÷Ê »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (263, 'please_fill_all_fields', 'Ì—ÃÏ «ﬂ„«· Ã„Ì⁄ «·ÕﬁÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (264, 'member_edited_successfully', ' „  ⁄œÌ· «·⁄÷Ê »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (265, 'add_member', '«÷«›… ⁄÷Ê', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (266, 'records_perpage', '«·”Ã·«  ›Ì «·’›Õ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (267, 'member_edit', ' ⁄œÌ· ⁄÷Ê', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (268, 'member_acc_type', '‰Ê⁄ «·Õ”«»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (269, 'send_msg_to_member', '√—”· —”«·… ··⁄÷Ê', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (270, 'acc_type_not_activated', '€Ì— „‰‘ÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (271, 'acc_type_activated', '„›⁄·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (272, 'acc_type_closed', '„€·ﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (273, 'leave_blank_for_no_change', '√ —ﬂÂ ›«—€« ·⁄œ„ «· €ÌÌ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (276, 'this_account_closed_cant_login', '⁄›Ê«, Â–« «·Õ”«» „€·ﬁ , €Ì— „’—Õ ·ﬂ »«·œŒÊ·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (277, 'this_account_not_activated', 'Œÿ√ , ·„ Ì „  ›⁄Ì· «·⁄÷ÊÌ… »⁄œ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (278, 'chng_email_msg_subject', ' √ﬂÌœ  €ÌÌ— »—Ìœﬂ «·≈·ﬂ —Ê‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (279, 'resend_activation_msg', '«⁄«œ… «—”«· —”«·… «· ›⁄Ì·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (280, 'invalid_pwd', 'Œÿ√, ﬂ·„… «·„—Ê— €Ì— ’ÕÌÕ…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (281, 'invalid_username', 'Œÿ√, «”„ «·„” Œœ„ €Ì— ’ÕÌÕ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (282, 'usercp_menu', 'ﬁ«∆„… «· Õﬂ„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (283, 'usercp_welcome_msg', '√Â·« »ﬂ Ì« {username} ›Ì ·ÊÕ… «· Õﬂ„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (284, 'cp_hooks_fix_order', ' — Ì»  ·ﬁ«∆Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (285, 'cp_hooks', '«·«÷«›«  «·»—„ÃÌ… «·„œ„Ã…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (286, 'no_hooks', '·«  ÊÃœ «÷«›« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (287, 'add', '«÷«›…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (288, 'the_place', '«·„ﬂ«‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (289, 'the_options', '«·ŒÌ«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (290, 'the_default_template', '«·ﬁ«·» «·«› —«÷Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (291, 'the_videos', '«·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (292, 'the_news', '«·√Œ»«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (293, 'the_votes', '«·«” › «∆« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (294, 'the_statics', '«·«Õ’«∆Ì« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (295, 'appearance_places', '√„«ﬂ‰ «·ŸÂÊ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (296, 'the_blocks', '«·ﬁÊ«∆„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (297, 'the_position', '«·„Êﬁ⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (298, 'right', 'Ì„Ì‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (299, 'center', 'Ê”ÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (300, 'left', 'Ì”«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (301, 'the_template', '«·ﬁ«·»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (302, 'to_up', '«·Ï «·√⁄·Ï', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (303, 'to_down', '«·Ï «·√”›·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (304, 'enable', ' ‰‘Ìÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (305, 'disable', ' ⁄ÿÌ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (306, 'cp_blocks_fix_order', ' ’ÕÌÕ  — Ì» «·ﬁÊ«∆„  ·ﬁ«∆Ì«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (307, 'cp_no_blocks', '·«  ÊÃœ ﬁÊ«∆„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (308, 'the_content', '«·„Õ ÊÏ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (309, 'logout', ' ”ÃÌ· Œ—ÊÃ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (310, 'the_settings', '«·≈⁄œ«œ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (311, 'do_button', ' ‰›Ì–', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (312, 'news_add', '«÷«›… Œ»—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (313, 'news_short_content', '«·‰’ «·Œ«—ÃÌ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (314, 'auto_short_content_create', '«‰‘«¡ «·‰’ «·Œ«—ÃÌ  ·ﬁ«∆Ì«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (315, 'the_date', '«· «—ÌŒ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (316, 'all', '«·ﬂ·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (317, 'view_do', '⁄—÷', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (318, 'os_and_browsers_statics', '«Õ’«∆Ì«  «·„ ’›Õ«  Ê «·‰Ÿ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (319, 'visitors_hits_statics', '«Õ’«∆Ì«  “Ì«—«  «·“Ê«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (320, 'online_visitors_statics', '«Õ’«∆Ì«  «·„ Ê«ÃœÊ‰ «·¬‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (321, 'default_style', '«·” «Ì· «·«› —«÷Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (322, 'search_min_letters', '√ﬁ· ⁄œœ ··√Õ—› ›Ì «·»ÕÀ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (323, 'sorry_search_disabled', '‰√”› ·ﬂ , ·ﬁœ ﬁ«„  «·«œ«—… » ⁄ÿÌ· «·»ÕÀ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (324, 'uploader_title', '—›⁄ «·„·›« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (325, 'pixel', '»Ìﬂ”·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (326, 'this_filetype_not_allowed', '‰Ê⁄ «·„·› €Ì— „”„ÊÕ »Â', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (327, 'the_file', '«·„·›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (328, 'auto_photos_resize', ' ’€Ì—  ·ﬁ«∆Ì ··’Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (329, 'upload_file_do', '—›⁄ «·„·›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (330, 'allowed_filetypes', '«·√‰Ê«⁄ «·„”„ÊÕ —›⁄Â«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (331, 'please_login_first', 'Ì—ÃÏ  ”ÃÌ· «·œŒÊ· «Ê·«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (332, 'uploader_thumb_width', '⁄—÷ «·„’€—… «·«› —«÷Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (333, 'uploader_thumb_hieght', 'ÿÊ· «·„’€—… «·«› —«÷Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (334, 'fixed', 'À«» ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (335, 'send2friend_failed', 'Œÿ√ √À‰«¡ «·«—”«· .. Õ«Ê· „—… «Œ—Ï', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (336, 'invalid_from_or_to_email', 'Ì—ÃÏ «· √ﬂœ „‰ ’Õ… »—Ìœﬂ «Ê »—Ìœ ’œÌﬁﬂ «·«·ﬂ —Ê‰Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (337, 'bnr_listen', '„·› «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (338, 'urls_fields', 'Œ«‰«  —Ê«»ÿ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (339, 'urls_fields_add', '«÷«›… —«»ÿ «÷«›Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (340, 'access_denied', '€Ì— „’—Õ »«·œŒÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (341, 'no_singers', '·« ÌÊÃœ „€‰ÌÌ‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (342, 'the_cat', '«·ﬁ”„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (343, 'singers_list', 'ﬁ«∆„… «·„€‰ÌÌ‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (344, 'singer', '„€‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (345, 'album', '«·»Ê„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (346, 'the_albums', '«·√·»Ê„« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (347, 'no_new_files', '·«  ÊÃœ „·›«  ÃœÌœ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (348, 'err_autosearch_folder_not_exists', '„Ã·œ «·»ÕÀ «· ·ﬁ«∆Ì €Ì— ’ÕÌÕ , Ì—ÃÏ «· √ﬂœ „‰ «”„ «·„Ã·œ Ê «· Ã—»… „—… «Œ—Ï', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (349, 'auto_search', '«·»ÕÀ «· ·ﬁ«∆Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (350, 'add_songs', '«÷«›… «€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (351, 'new_songs_menu', 'ﬁ«∆„… ÃœÌœ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (352, 'new_stores_menu', 'ﬁ«∆„… ÃœÌœ «·”Êﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (353, 'the_banners', '«·«⁄·«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (354, 'users_and_permissions', '«·„” Œœ„Ì‰ Ê «· ’«—ÌÕ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (355, 'permissions_manage', '«œ«—… «· ’«—ÌÕ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (356, 'cp_sections_permissions', '’·«ÕÌ«  «·œŒÊ· ··√ﬁ”«„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (357, 'videos_cats_permissions', ' ’«—ÌÕ √ﬁ”«„ «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (358, 'songs_cats_permissions', ' ’«—ÌÕ √ﬁ”«„ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (359, 'cp_err_username_exists', 'Œÿ√ .. «”„ «·„” Œœ„ «·–Ì ﬁ„  »≈œŒ«·Â „ÊÃÊœ „”»ﬁ«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (360, 'cp_plz_enter_usr_pwd', 'Ì—ÃÏ «œŒ«· «”„ «·„” Œœ„ Ê ﬂ·„… «·„—Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (361, 'cp_edit_user_success', ' „  ⁄œÌ· «·„” Œœ„ »‰Ã«Õ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (362, 'cp_add_user', '«÷«›… „” Œœ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (363, 'cp_email', '«·»—Ìœ «·≈·ﬂ —Ê‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (364, 'cp_user_group', '«·— »…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (365, 'cp_user_admin', '„œÌ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (366, 'cp_user_mod', '„‘—›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (367, 'the_users', '«·„” Œœ„Ì‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (368, 'edit_personal_acc_only', '’·«ÕÌ« ﬂ ·«  ”„Õ ≈·« » ⁄œÌ· Õ”«»ﬂ «·‘Œ’Ì ›ﬁÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (369, 'click_here_to_edit_ur_account', '· ⁄œÌ· Õ”«»ﬂ ≈÷€ÿ Â‰«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (372, 'the_pages', '«·’›Õ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (373, 'pages_add', '«÷«›… ’›Õ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (374, 'no_pages', '·«  ÊÃœ ’›Õ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (375, 'err_cat_access_denied', '·« „·ﬂ «·’·«ÕÌ«  ··œŒÊ· «·Ï Â– «·ﬁ”„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (376, 'songs_custom_fields', 'Œ«‰«  «·√€«‰Ì «·«÷«›Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (377, 'songs_field_add', '«÷«›… Œ«‰… ÃœÌœ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (378, 'no_data', '·«  ÊÃœ »Ì«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (381, 'songs_default_orderby', '«· — Ì» «·«› —«÷Ì ··√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (380, 'field_style', ' ‰”Ìﬁ «÷«›Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (382, 'asc', ' ’«⁄œÌ«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (383, 'desc', ' ‰«“·Ì«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (384, 'visitors_can_sort_songs', '«„ﬂ«‰Ì… «·“Ê«— „‰ «Œ Ì«—  — Ì» «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (386, 'the_most_voted', '«·√ﬂÀ—  ﬁÌÌ„«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (387, 'songs_orderby_text', '«· — Ì» Õ”»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (388, 'the_download', '«· Õ„Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (389, 'download_for_all_visitors', '„› ÊÕ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (390, 'download_for_members_only', '··√⁄÷«¡ ›ﬁÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (391, 'stng_videos_download_for_members_only', ' Õ„Ì· «·ﬂ·Ì»«  ··√⁄÷«¡ ›ﬁÿ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (392, 'add_to_playlist', '«÷«›… «·Ï ﬁ«∆„… «· ‘€Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (393, 'stng_songs_multi_select', '«„ﬂ«‰Ì… «·“Ê«— „‰ «· ÕœÌœ «·„ ⁄œœ ··√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (394, 'playlists_add', '«÷«›… ﬁ«∆„…  ‘€Ì· ÃœÌœ…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (395, 'playlists_del', 'Õ–› ﬁ«∆„… «· ‘€Ì· «·Õ«·Ì…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (396, 'printable_copy', '‰”Œ… ··ÿ»«⁄…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (397, 'members_playlists_table', 'ÃœÊ· ﬁÊ«∆„ «· ‘€Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (398, 'singers_other_letters', '€Ì— –·ﬂ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (399, 'the_favorite', '«·„›÷·…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (400, 'no_files', '·«  ÊÃœ „·›« ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (401, 'send_new_msg', '«—”· —”«·… ÃœÌœ…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (402, 'the_messages', '«·—”«∆·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (403, 'used_messages', '—”«·… „” ⁄„·…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (404, 'pm_box_full_warning', ' Õ–Ì— : »—Ìœﬂ „„ ·Ì¡ , ·‰   „ﬂ‰ „‰ «” ﬁ»«· «Ì —”«∆· ÃœÌœ…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (405, 'no_messages', '·«  ÊÃœ —”«∆·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (406, 'the_sender', '«·„—”·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (407, 'the_subject', '«·„Ê÷Ê⁄', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (408, 'reply', '—œ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (409, 'err_sendto_pm_box_full', 'Œÿ√ : «·»—Ìœ «·–Ì  Õ«Ê· «·«—”«· «·ÌÂ „„ ·Ì¡', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (410, 'pm_sent_successfully', '·ﬁœ  „ «—”«· —”«· ﬂ »‰Ã«Õ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (411, 'err_sendto_username_invalid', 'Œÿ√ .. «”„ «·„” Œœ„ «·„—”· «·ÌÂ €Ì— ’ÕÌÕ . Ì—ÃÏ «· √ﬂœ „‰Â Ê «·„Õ«Ê·… „—… «Œ—Ï', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (412, 'the_message', '«·—”«·…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (413, 'chng_email_conf_msg_sent', ' „ «—”«· —”«·… ·ﬂ  Õ ÊÌ —«»ÿ  ›⁄Ì· »—Ìœﬂ «·«·ﬂ —Ê‰Ì «·ÃœÌœ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (414, 'your_profile_updated_successfully', ' „  ÕœÌÀ »Ì«‰« ﬂ »‰Ã«Õ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (415, 'the_profile', '«·„·› «·‘Œ’Ì', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (416, 'default_playlist', '«·ﬁ«∆„… «·«› —«÷Ì…', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (417, 'err_wrong_uploader_folder', 'Œÿ√ ›Ì „Ã·œ «· Õ„Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (418, 'register_email_exists2', '«–« ﬂ«‰ Â–« ÂÊ »—Ìœﬂ «·«·ﬂ —Ê‰Ì Ê ‰”Ì»  ﬂ·„… «·„—Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (419, 'the_statics_and_counters', '«·«Õ’«∆Ì«  Ê «·⁄œ«œ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (420, 'cp_visitors_statics', '«Õ’«∆Ì«  «·“Ê«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (421, 'cp_counters_start_date', ' «—ÌŒ »œ¡ «·⁄œ«œ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (422, 'cp_total_visits', '„Ã„Ê⁄ «·“Ì«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (423, 'the_hour', '«·”«⁄…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (424, 'operating_systems', '√‰Ÿ„… «· ‘€Ì·', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (425, 'the_browsers', '«·„ ’›Õ« ', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (426, 'monthly_statics_for', '≈Õ’«∆Ì«  «·“Ê«— «·‘Â—Ì… ·⁄«„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (427, 'daily_statics_for', '≈Õ’«∆Ì«  «·“Ê«— «·ÌÊ„Ì… ·‘Â—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (428, 'the_year', '«·⁄«„', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (429, 'the_month', '«·‘Â—', 'main');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (430, 'right_to_left', '„‰ «·Ì„‰ «·Ï «·Ì”«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (431, 'left_to_right', '„‰ «·Ì”«— «·Ï «·Ì„Ì‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (432, 'page_dir', '« Ã«Â «·’›Õ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (433, 'mailing_email', '»—Ìœ «·„—«”·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (434, 'copyrights_sitename', '«”„ «·„Êﬁ⁄ ›Ì ‰’ «·ÕﬁÊﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (435, 'section_name', '«”„ «·ﬁ”„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (436, 'site_name', '«”„ «·„Êﬁ⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (437, 'page_keywords', 'ﬂ·„«  „”«⁄œ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (438, 'votes_expire_time', '«·Êﬁ  «·›«’· ›Ì «·«” › «∆« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (439, 'hour', '”«⁄…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (440, 'the_songs_cats', '√ﬁ”«„ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (441, 'the_songs_and_singers', '«·„€‰Ì‰ Ê «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (442, 'the_songs_comments', ' ⁄·Ìﬁ«  «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (443, 'add_edit_videos', '≈÷«›… /  ⁄œÌ· «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (444, 'bnr_views', 'ŸÂÊ—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (445, 'bnr_visits', '“Ì«—…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (446, 'del_cat_warning', ' Õ–Ì— : Õ–› Â–« «·ﬁ”„ ”Ê› ÌƒœÌ «·Ï Õ–› Ã„Ì⁄ «·„€‰ÌÌ‰ Ê «·√€«‰Ì «· Ì ÌÕ ÊÌÂ« , Â·  —Ìœ «·„ «»⁄… ø', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (447, 'show_download_icon', '«ŸÂ«— «ÌﬁÊ‰… «· Õ„Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (448, 'the_download_icon', '«ÌﬁÊ‰… «· Õ„Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (449, 'download_icon_alt', 'Ê’› √ÌﬁÊ‰… «· Õ„Ì·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (450, 'show_listen_icon', '«ŸÂ«— «ÌﬁÊ‰… «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (451, 'the_listen_icon', '√ÌﬁÊ‰… «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (452, 'listen_icon_alt', 'Ê’› √ÌﬁÊ‰… «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (453, 'listen_file_mime', '‰Ê⁄ „·› «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (454, 'listen_file_name', '«”„ „·› «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (455, 'listen_file_content', '„Õ ÊÏ „·› «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (456, 'the_cats', '«·√ﬁ”«„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (457, 'del_video_cat_warning', 'Õ–› Â–« «·ﬁ”„ ”Ê› ÌƒœÌ «·Ï Õ–› Ã„Ì⁄ «·ﬂ·Ì»«  «· Ì ÌÕ ÊÌÂ« , Â·  —Ìœ «·„ «»⁄… ø', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (458, 'add_video', '«÷«›… ﬂ·Ì»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (459, 'add_cat', '«÷«›… ﬁ”„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (460, 'no_videos_or_no_permissions', '·« ÊÃœ ﬂ·Ì»«  «Ê «‰ﬂ ·«  „·ﬂ «·’·«ÕÌ«  ·„‘«Âœ… Â–« «·ﬁ”„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (461, 'default', '«› —«÷Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (462, 'view_page', '„‘«Âœ… «·’›Õ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (463, 'vote_add', '«÷«›…  ’ÊÌ  ÃœÌœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (464, 'set_default', ' ⁄ÌÌ‰ «› —«÷Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (465, 'edit_or_options', ' ⁄œÌ· / ŒÌ«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (466, 'add_options', '«÷«›… ŒÌ«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (467, 'vote_files_expire_time', '«·Êﬁ  «·›«’· ›Ì  ﬁÌÌ„ «·„·›« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (468, 'images_cells_count', '⁄œœ √⁄„œ… «·’Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (469, 'news_perpage', '⁄œœ «·√Œ»«— ›Ì «·’›Õ… «·Ê«Õœ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (470, 'back_to_cats', '«·—ÃÊ⁄ «·Ï «·√ﬁ”«„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (471, 'singer_add', '«÷«›… „€‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (472, 'no_singers_or_no_permissions', '·« ÌÊÃœ „€‰ÌÌ‰ «Ê «‰ﬂ ·«  „·ﬂ ’·«ÕÌ«  ·≈œ«—… „Ã„Ê⁄«  «·„€‰ÌÌ‰ Â–Â', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (473, 'move_songs', '‰ﬁ· «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (474, 'move_from', '‰ﬁ· „‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (475, 'move_to', '‰ﬁ· «·Ï', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (476, 'please_select_songs_first', 'Ì—ÃÏ  ÕœÌœ «·√€«‰Ì √Ê·«', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (477, 'next', '«· «·Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (478, 'without_album', '»œÊ‰ √·»Ê„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (479, 'the_album', '«·√·»Ê„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (480, 'move_do', '‰ﬁ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (481, 'back_to_singers', '«·—ÃÊ⁄ «·Ï «·„€‰ÌÌ‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (482, 'edit_singer', ' ⁄œÌ· «·„€‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (483, 'del_singer_warning', 'Õ–› «·„€‰Ì ”Ê› ÌƒœÌ «·Ï Õ–› Ã„Ì⁄ √·»Ê„« Â Ê √€«‰Ì .. Â·  —Ìœ «·„ «»⁄… ø ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (484, 'song', '√€‰Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (485, 'select_all', ' ÕœÌœ «·ﬂ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (486, 'select_none', '«·€«¡ «· ÕœÌœ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (487, 'change_comment', ' €ÌÌ— «· ⁄·Ìﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (488, 'move_to_album', '«‰ﬁ·Â„ «·Ï «·√·»Ê„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (489, 'move_to_singer', '‰ﬁ· «·Ï „€‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (490, 'edit_songs', ' ⁄œÌ· «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (491, 'delete_songs', 'Õ–› «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (492, 'add_to_new_songs_menu', '«÷«›… «·Ï ÃœÌœ «·«€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (493, 'without_comment', '»œÊ‰  ⁄·Ìﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (494, 'the_comment', '«· ⁄·Ìﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (495, 'fields_count', '⁄œœ «·ÕﬁÊ·', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (496, 'edit_album', ' ⁄œÌ· «·√·»Ê„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (497, 'singers_count', '⁄œœ «·„€‰Ì‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (498, 'songs_count', '⁄œœ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (499, 'videos_count', '⁄œœ «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (500, 'users_count', '⁄œœ «·„” Œœ„Ì‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (501, 'show_sitename_in_subpages', '«ŸÂ«— «”„ «·„Êﬁ⁄ ›Ì «·’›Õ«  «·›—⁄Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (502, 'show_section_name_in_subpages', '«ŸÂ«— «”„ «·ﬁ”„ ›Ì «·’›Õ«  «·›—⁄Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (503, 'adding_songs_fields_count', '⁄œœ «·ÕﬁÊ· ›Ì «÷«›… «·«€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (504, 'songs_perpage', '⁄œœ «·√€«‰Ì ›Ì «·’›Õ… «·Ê«Õœ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (505, 'videos_perpage', '⁄œœ «·ﬂ·Ì»«  ›Ì «·’›Õ… «·Ê«Õœ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (506, 'msgs_count_limit', 'Õœ «·—”«∆· «·Œ«’…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (507, 'message', '—”«·…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (508, 'stng_singers_letters', '‘—Ìÿ «·Õ—Ê› ··„€‰ÌÌ‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (509, 'stng_songs_letters', '‘—Ìÿ «·Õ—Ê› ··√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (510, 'stng_vote_songs', ' ﬁÌÌ„ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (511, 'stng_send_song', '«—”«· «·√€‰Ì… ·’œÌﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (512, 'stng_group_singers_by_letters', '⁄—÷ «·„€‰ÌÌ‰ ›Ì „Ã„Ê⁄«  Õ”» «·Õ—›', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (513, 'stng_vote_videos', ' ﬁÌÌ„ «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (514, 'stng_send_videos', '«—”«· «·ﬂ·Ì»«  ·’œÌﬁ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (515, 'the_listen_file', '„·› «·«” „«⁄', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (516, 'ram_banner_width', '⁄—÷ ‰«›–… «·«⁄·«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (517, 'ram_banner_height', 'ÿÊ· ‰«›–… «·«⁄·«‰« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (518, 'listen_statics_rest_done', ' „  ’›Ì— ⁄œ«œ«  «” „«⁄ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (519, 'download_statics_rest_done', ' „  ’›Ì— ⁄œ«œ«   Õ„Ì· «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (520, 'votes_statics_rest_done', ' „  ’›Ì— ⁄œ«œ«   ﬁÌÌ„ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (521, 'videos_watch_rest_done', ' „  ’›Ì— ⁄œ«œ«  „‘«Âœ… «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (522, 'videos_download_rest_done', ' „  ’›Ì— ⁄œ«œ«   Õ„Ì· «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (523, 'videos_votes_rest_done', ' „  ’›Ì— ⁄œ«œ«   ﬁÌÌ„ «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (524, 'songs_listens_statics', '«” „«⁄ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (525, 'songs_downloads_statics', ' Õ„Ì· «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (526, 'songs_votes_statics', ' ﬁÌÌ„ «·√€«‰Ì', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (527, 'videos_watch_statics', '„‘«Âœ… «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (528, 'videos_download_statics', ' Õ„Ì· «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (529, 'videos_votes_statics', ' ﬁÌÌ„ «·ﬂ·Ì»« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (530, 'err_invalid_song_id', '<b>Œÿ√ : </b> Ì—ÃÏ «· √ﬂœ „‰ —ﬁ„ «·«€‰Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (531, 'song_id', '—ﬁ„ «·«€‰Ì…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (532, 'err_invalid_id', '<b>Œÿ√ : </b> Ì—ÃÏ «· √ﬂœ „‰ «·—ﬁ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (533, 'the_id', '«·—ﬁ„', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (534, 'without_title', '»œÊ‰ ⁄‰Ê«‰', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (535, 'cp_rest_counters', ' ’›Ì— «·⁄œ«œ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (536, 'cp_rest_counters_do', ' ’›Ì— «·⁄œ«œ« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (537, 'visitors_statics_rest_done', ' „  ’›Ì— ⁄œ«œ«  «·“Ê«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (538, 'cp_no_phrases', '·«  ÊÃœ ⁄»«—« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (539, 'cp_no_templates', '·«  ÊÃœ ﬁÊ«·»', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (540, 'cp_invalid_pwd', 'ﬂ·„… «·„—Ê— €Ì— ’ÕÌÕ…', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (541, 'cp_invalid_username', '«”„ «·„” Œœ„ €Ì— ’ÕÌÕ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (542, 'cp_welcome_msg', '√Â·« Ê ”Â·« »ﬂ Ì« {username}', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (543, 'cp_statics', '«Õ’«∆Ì« ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (544, 'search', '»ÕÀ', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (545, 'forgot_pwd_msg_subject', '«” —Ã«⁄ ﬂ·„… «·„—Ê—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (546, 'without_selection', '»œÊ‰ «Œ Ì«—', 'cp');
INSERT INTO `songs_phrases` (`id`, `name`, `value`, `cat`) VALUES (547, 'create_main_user', '«‰‘«¡ «·„” Œœ„ «·—∆Ì”Ì', 'cp');

-- --------------------------------------------------------

-- 
-- Table structure for table `songs_phrases_cats`
-- 

DROP TABLE IF EXISTS `songs_phrases_cats`;
CREATE TABLE `songs_phrases_cats` (
  `id` text NOT NULL,
  `name` text NOT NULL,
  PRIMARY KEY  (`id`(20))
) ;

-- 
-- Dumping data for table `songs_phrases_cats`
-- 

INSERT INTO `songs_phrases_cats` (`id`, `name`) VALUES ('main', '&#1575;&#1604;&#1593;&#1576;&#1575;&#1585;&#1575;&#1578; &#1575;&#1604;&#1593;&#1575;&#1605;&#1577;');
INSERT INTO `songs_phrases_cats` (`id`, `name`) VALUES ('cp', '&#1604;&#1608;&#1581;&#1577; &#1575;&#1604;&#1578;&#1581;&#1603;&#1605; / &#1575;&#1604;&#1606;&#1592;&#1575;&#1605;');
